name: Node.js CI

on:
  pull_request:
    branches: ['main', 'test-branch']
  repository_dispatch:
    types: [contentful.deploy]
  schedule:
    - cron: '35 9 * * *'


jobs:
  bob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
      - run: npm install
      - run: npx prettier . --write
      - run: npm run test
      - run: npx prettier . --check
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'

    needs: [bob]
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod

