name: Node.js CI

on:
  pull_request:
    branches: ['main', 'test-branch']

jobs:
  bob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint

