name: Node.js CI

on:
  push:                    # corre em todos os pushes
    branches: ['**']
  # pull_request:           # corre em pull requests para o main (versão antiga da pipeline)
  #   branches: ['main']
  repository_dispatch:      #corre em updates do contentful
    types: [contentful.deploy]
  # schedule:               #corre todos os dias à meia-noite (UTC Time)
  #   - cron: '0 0 * * *' 


jobs:
  bob:                     
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pretier, Jest & ESLint
        uses: actions/setup-node@v3
      - run: npm install             #instala dependências
      - run: npx prettier . --write  #formata ficheiros
      - run: npm run test            #testa código com o Jest
      - run: npx prettier . --check  #confirma formatação
      - run: npm run lint            #ESLint

  deploy:
    runs-on: ubuntu-latest
    if:  github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'

    #|| github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'    # corre em pull requests para o main (versão antiga da pipeline)

    needs: [bob]   #só corre em caso de sucesso do bob (continue-on-error está definido false por defeito)
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: actions/setup-node@v3
      - run: npm install     #instala dependências
      - run:  npm run build  #build
        env:  #variáveis do Contentful
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CTFL_SPACE }}
      - run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod  #deploy para netlify
